name: movi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  provider: ^6.1.2
  dartz: ^0.10.1
  carousel_slider: ^5.0.0
  infinite_scroll_pagination: ^4.1.0
  get_it: ^8.0.2
  webview_flutter: ^4.4.4
  youtube_player_flutter: ^9.1.1
  flutter_native_splash: ^2.4.3
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/